// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Elmish.DragAndDrop")>]
[<assembly: AssemblyProductAttribute("Elmish.DragAndDrop")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-07-25T00:00:00.0000000-04:00")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.4.0")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","rc")>]
[<assembly: AssemblyMetadataAttribute("GitHash","0cb352902119761a1ed50689148df252cc3a008c")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Elmish.DragAndDrop"
    let [<Literal>] AssemblyProduct = "Elmish.DragAndDrop"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-07-25T00:00:00.0000000-04:00"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyInformationalVersion = "0.4.0"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "rc"
    let [<Literal>] AssemblyMetadata_GitHash = "0cb352902119761a1ed50689148df252cc3a008c"
